---
- name: install composer
  shell: curl -s http://getcomposer.org/installer | php chdir=/usr/local/bin creates=/usr/local/bin/composer


- name: rename composer binary
  command: mv composer.phar composer chdir=/usr/local/bin creates=/usr/local/bin/composer
