---
- name: install php extensions
  apt: pkg={{ item }}
       state=present
       update_cache=yes

  with_items:
  - php7.0-mysql
  - php7.0-cli
  - php7.0-curl
  - php7.0-gd
  - php7.0-mcrypt
  - php7.0-json
  - php7.0-xml
